### ISSUE TITLE
Add pager support

### ISSUE THREAD

**Issue by ismaelgv** [alexhallam/tv#112]
It would be useful to have a pager mode that does not cuts the number of rows but lets you explore the data (including the colorization). This support could be inside the tool or just for external pagers such as `less` or `bat`.

I have tried to use less in a pipe but I lose the colors:
```sh
tidy-viewer data.csv -n 10000 -c 1 | less -R
```

Thanks for this awesome tool, great job here!

**Comment by alexhallam** [comment]
Thanks for opening this issue. 

1. The color loss with `less` is on purpose. We strip text of all color properties in this case. https://github.com/alexhallam/tv/issues/73
2. I also want the ability to page, but `tv` will not be the tool for this. I have plans for another data tool that I hope will have pager-like support, but I don't want to say too much about that now because I need to test the viability.

**Comment by alexhallam** [comment]
As a side note, great repo https://github.com/ismaelgv/rnr!

**Comment by ismaelgv** [comment]
Thanks for the quick response!

> 1. The color loss with `less` is on purpose. We strip text of all color properties in this case. https://github.com/alexhallam/tv/issues/73

Maybe a new flag could be added to always keep the color (or just when color flag is explicitly set). This way the `tv` out can be piped to `less` with `-R` flag and keep the coloring with the pager.

If no flag is passed, it just keep the current behavior.

> 2. I also want the ability to page, but `tv` will not be the tool for this. I have plans for another data tool that I hope will have pager-like support, but I don't want to say too much about that now because I need to test the viability. 

Great, I am eager to check this new tool. ;)

**Comment by alexhallam** [comment]
I think you are onto something.

I will block out some time to test a `--force-color` flag with the assumption that it will be piped to `less -R`.

**Comment by alexhallam** [comment]
I just pushed a branch.

Do you mind being a tester?

`git clone https://github.com/alexhallam/tv/tree/force_color`
`cd tv`
`cargo build`
`./target/debug/tidy-viewer -a data/titanic.csv -n 1000 | less -R`

**Comment by ismaelgv** [comment]
@alexhallam works great.  :wink: 

I've tested the new `-a` flag piping the results to `less -R` and `bat -p`. They both displays the colors correctly.

This should be more than enough to keep going. However, related to the other point that I initially included in the issue, should `-n 0` (or something similar) display all lines instead of using a very large value (`-n 1000`)? Does it makes sense to you?

**Comment by alexhallam** [comment]
I see the logic in `-n 0`. I personally don’t think it is worth the additional feature.

**Comment by alexhallam** [comment]
#113
