### ISSUE TITLE
Package for Red Hat

### ISSUE THREAD

**Issue by alexhallam** [alexhallam/tv#118]
Many AWS servers default to red hat servers that use `yum` for package install. It would ne nice to have a build for this distribution. 

Can `tv` be snap installed on AWS machines?

**Comment by alexhallam** [comment]
For reference this is the `carbo-deb` utility https://github.com/kornelski/cargo-deb/tree/f2fcf565741dc6222a99eb62b10fcb8913ee2b2f

**Comment by eddelbuettel** [comment]
Yes that is what I am saying. I am aware that `alien` has been used for years (decades even...) to 'unpack' from one format, and use the existing meta-data to create a package in the other format.  Initially written by a former Debian maintainer, but I understand it has been used 'to and fro'.  As you ship a static binary anyway there is no issue with library mappings, and you have no pre/post install scripts so it is really just a matter of turning a `.deb` (a `cpio` archive around inner tarballs) into an `.rpm`.  

It may even work :)

**Comment by alexhallam** [comment]
I know exactly where that is coming from. This is the mistake that I thought was giving you issues on the deb package. I bumped the version name name in my [cargo.toml](https://github.com/alexhallam/tv/blob/c8e5c37fc374364b7b5016573c7712a629845046/Cargo.toml#L11), but there is virtually no code changes between 1.4.3 and 1.4.4. I have not merged anything yet.

**Comment by alexhallam** [comment]
From your example I think I know what I need to know to get rpm releases automated in github actions. 

Thanks for the example and making me aware of `alien`

**Comment by alexhallam** [comment]
I was able to run this all locally. I would like to add automated builds of the rpm package, but for now I updated my [realease wiki](https://github.com/alexhallam/tv/wiki) with this command.
