### ISSUE TITLE
Where is the .deb?

### ISSUE THREAD

**Issue by benoitjy** [alexhallam/tv#121]
Hi,

i try to download tv.
In readme.md : "installation" "debian"
`wget https://github.com/alexhallam/tv/releases/download/<VERSION>/tidy-viewer_<VERSION>_amd64.deb`
ok, version is 1.4.3, then:
`wget https://github.com/alexhallam/tv/releases/download/1.4.3/tidy-viewer_1.4.3_amd64.deb`
not found.
where is my mistake?

**Comment by alexhallam** [comment]
Sorry, I did not upload that on this version. I am on it.

**Comment by alexhallam** [comment]
I just uploaded it here. I need to add `cargo-deb` to GHA.

https://github.com/alexhallam/tv/releases/tag/1.4.3

**Comment by benoitjy** [comment]
Nice, thank you!

**Comment by alexhallam** [comment]
My pleasure!
