### ISSUE TITLE
Add `cargo-deb` to GHA

### ISSUE THREAD

**Issue by alexhallam** [alexhallam/tv#122]
I need to add cargo-deb to GHA to make sure that I don't forget to add this binary to the release.

**Comment by RishiKumarRay** [comment]
can you elaborate this please

**Comment by alexhallam** [comment]
Yes!

Every release except for the debian release is generated automatically in the workflow yaml file. In the final step of this file the archives are pushed to the releases. Here is the section that toes the pushing https://github.com/alexhallam/tv/blob/c8e5c37fc374364b7b5016573c7712a629845046/.github/workflows/release.yml#L157

At some point, before the archives are pushed `cargo-deb` should be run inside the tv directory. This will automatically generate the proper debian file named `tidy-viewer_<VERSION>_amd64.deb`. 

I am not sure where to put the `cargo-deb` command, I would have to spend some time looking at the workflow. 

From what I can tell at this point I imagine there will me two lines added

1. `cargo-deb`
2. pushing the `tidy-viewer_<VERSION>_amd64.deb` to the same location the other releases are going.

**Comment by alexhallam** [comment]
I was testing this last night and was hitting memory problems on GHA. I am going to temporarily close this for now. The manual upload may be the best I can do at this time.
