### ISSUE TITLE
Homebrew update/install fails with SHA mismatch

### ISSUE THREAD

**Issue by tomshafer** [alexhallam/tv#129]
Not urgent, but FYI:

```
~ $ brew update && brew upgrade tidy-viewer
Already up-to-date.
==> Upgrading 1 outdated package:
alexhallam/tidy-viewer/tidy-viewer 1.4.3 -> 1.4.5
==> Downloading https://github.com/alexhallam/tv/releases/download/1.4.3/tidy-viewer--x86_64-apple-darwin
Already downloaded: [...]/Caches/Homebrew/downloads/def23c2288ff52abd6d39369986336a169881983a0d8d22d33e351f53db4e9b2--tidy-viewer--x86_64-apple-darwin.tar.gz
Error: SHA256 mismatch
Expected: 63233fbd215293e50edcb47d36bbab05975f19000e74bf25a8e6d161886492c0
  Actual: f79e7481add98af9a52a83bbc23e075e06be1af09f6b8f94315bc58d8216d90a
    File: [...]/Caches/Homebrew/downloads/def23c2288ff52abd6d39369986336a169881983a0d8d22d33e351f53db4e9b2--tidy-viewer--x86_64-apple-darwin.tar.gz
To retry an incomplete download, remove the file above.
```

**Comment by alexhallam** [comment]
Thanks Tom. I am getting some guidance on how to update packages on Homebrew-core. It is new for me so I have some homework to do.

**Comment by alexhallam** [comment]
Can you let me know if you can run `brew install --build-from-source tidy-viewer` without error? This works on my machine, but I am not sure if that is because the source is the same system architecture.

**Comment by tomshafer** [comment]
Yep, the above works fine! Like I say, no rush—but if you hadn't seen it I wanted to let you know!

**Comment by alexhallam** [comment]
Thanks for pointing it out. I want to fix this ASAP. The package gets many homebrew downloads so I do not want the bug to last for long.

**Comment by alexhallam** [comment]
Okay, I think the issue was that you are updating from my personal homebrew-tap, which had a missmatch, I am going to make an issue to depreciate my personal tap in favor of using the homebrew-core formula. That will make it a little easier to manage.

I just fixed the missmatch on my tap. Could you let me know if it is working when you get a chance?

**Comment by tomshafer** [comment]
Works fine now, thank you. I'll move over to homebrew-core, though. Have a nice weekend!
