### ISSUE TITLE
Add light mode

### ISSUE THREAD

**Issue by jwuphysics** [alexhallam/tv#135]
I noticed that none of the built-in color palettes work well with my light mode terminal (I use solarized light). It would be nice to add in at least one light mode palette!

**Comment by alexhallam** [comment]
Not a problem. I can add a light solarized theme. Since you are asking I will let you tell me what number you want it associated with. Also, you may already know this but you can define any color scheme you want in a config.

**Comment by jwuphysics** [comment]
> Not a problem. I can add a light solarized theme. Since you are asking I will let you tell me what number you want it associated with.

Thanks! Maybe it can be (6)solarized_light, assuming that the current highest number is (5)uncolor. 

> Also, you may already know this but you can define any color scheme you want in a config.

I had tried to define a Solarized Light color scheme based on the palette [shown on Wikipedia](https://en.wikipedia.org/wiki/Solarized#Colors):
```
meta_color = [108, 113, 193]
header_color = [88, 110, 117]
std_color = [131, 148, 150]
na_color = [220, 50, 47]
neg_num_color = [42, 161, 152]
```
I threw these into `$HOME/Library/Application\ Support/tv.toml` but that didn't seem to work for me. (Note that I didn't rebuild `tv` so perhaps that was the issue?)

**Comment by alexhallam** [comment]
I will add those colors to ship with tv!

**Comment by alexhallam** [comment]
I used your colors with a solarized theme. How does this look.

![image](https://user-images.githubusercontent.com/9298693/178088481-e0e2623c-4ef3-4c4d-88db-da9673e9b85e.png)

**Comment by jwuphysics** [comment]
Thanks for the update. It looks great to me!
