### ISSUE TITLE
Crashes when opening empty files

### ISSUE THREAD

**Issue by nordenskiold** [alexhallam/tv#137]
Hi,

First off, thanks for providing such an awesome tool! This is a really minor thing, but thought I'd leave a note in case it hadn't been noticed before.

The first time I used this tool I accidentally tried opening an empty .csv and was met with:
`thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', src/main.rs:362:23`

Spent some time trying to figure out what was wrong with my installation before finally checking the csv and realizing it was just empty :man_facepalming: 

Could be nice to catch this and display a message to the user instead.

**Version:** tv 1.4.5

using --debug-mode flag I get the additional output:
`"StringRecord"
[]
`

Cheers

**Comment by alexhallam** [comment]
Thanks for using `tv`. I have been working on more error handling on the csv reading. I will see if I can toss in an empty file condition.

**Comment by alexhallam** [comment]
#148 is a pr for this
