### ISSUE TITLE
Is it possible to turn off dimensions printing?

### ISSUE THREAD

**Issue by atsalolikhin-spokeo** [alexhallam/tv#138]
Hi!  Thanks for a great utility!  

Is there any way to turn off the printing of the dimensions?  I just want to see the data.

**Comment by alexhallam** [comment]
Sure. Tell me what you would like the flag to be called.

**Comment by atsalolikhin-spokeo** [comment]
Wow!  Thanks!

Whatever you like -- how about `-D, --no-dimensions`  ?  :)

**Comment by alexhallam** [comment]
![image](https://user-images.githubusercontent.com/9298693/180611004-b2c30687-4ed5-442a-b82c-6f2687d45051.png)

Here is the implimentation

**Comment by atsalolikhin-spokeo** [comment]
Beauty!  Thank you very much!
