### ISSUE TITLE
Is it possible to turn off row numbering?

### ISSUE THREAD

**Issue by atsalolikhin-spokeo** [alexhallam/tv#139]
Is it possible to turn off row numbering, please?

I don't see an existing flag...  Maybe something like `-R, --no-row-numbering` ?

I just want to see the data.  :)

**Comment by alexhallam** [comment]
Would this include turning off the footer info?

**Comment by alexhallam** [comment]
How is this #142?

![image](https://user-images.githubusercontent.com/9298693/180616698-44cef580-e2a9-4f52-b251-f6bc70cf8b5c.png)

**Comment by atsalolikhin-spokeo** [comment]
Perfect! Thank you very much!
