### ISSUE TITLE
Would you mind cutting a new Homebrew release, please?

### ISSUE THREAD

**Issue by atsalolikhin-spokeo** [alexhallam/tv#145]
Hi Alex,

Would you mind cutting a new Homebrew release, please, with the recent bug fix and enhancements?

- https://github.com/alexhallam/tv/issues/138
- https://github.com/alexhallam/tv/issues/139
- https://github.com/alexhallam/tv/issues/140

Thanks for such a handy tool!

Thanks,
Aleksey

**Comment by alexhallam** [comment]
I am happy to. I am just a little behind on the home brew release.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Aleksey Tsalolikhin ***@***.***>
Sent: Tuesday, July 26, 2022 12:56:28 PM
To: alexhallam/tv ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [alexhallam/tv] Would you mind cutting a new Homebrew release, please? (Issue #145)


Hi Alex,

Would you mind cutting a new Homebrew release, please, with the recent bug fix and enhancements?

Thanks for such a handy tool!

Thanks,
Aleksey

**Comment by alexhallam** [comment]
This is just waiting on the Homebrew core team to merge `1.4.6`. https://github.com/Homebrew/homebrew-core/pull/106452

**Comment by alexhallam** [comment]
@atsalolikhin-spokeo can you confirm that you can get the latest `1.4.6` on homebrew?

**Comment by atsalolikhin-spokeo** [comment]
Yes!  Thank you!!

```
$ brew upgrade tidy-viewer
==> Upgrading 1 outdated package:
tidy-viewer 1.4.5 -> 1.4.6
==> Downloading https://ghcr.io/v2/homebrew/core/tidy-viewer/manifests/1.4.6
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/tidy-viewer/blobs/sha256:dcfe3cd819e556c49a4c6
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:dcfe3cd819
######################################################################## 100.0%
==> Upgrading tidy-viewer
  1.4.5 -> 1.4.6

==> Pouring tidy-viewer--1.4.6.big_sur.bottle.tar.gz
🍺  /Users/atsalolikhin/git/homebrew/Cellar/tidy-viewer/1.4.6: 8 files, 2.6MB
==> Running `brew cleanup tidy-viewer`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Removing: /Users/atsalolikhin/git/homebrew/Cellar/tidy-viewer/1.4.5... (8 files, 2.5MB)
Removing: /Users/atsalolikhin/Library/Caches/Homebrew/tidy-viewer--1.4.5... (926.6KB)
$ tv --version
tv 1.4.6
$
```
