### ISSUE TITLE
An error link in README.md

### ISSUE THREAD

**Issue by chasing-freedom** [alexhallam/tv#149]
Chapter: [Tools to pair with tv](https://github.com/alexhallam/tv#tools-to-pair-with-tv)
> [q](https://github.com/zestyping/q) - Command line csv data manipulation query-like. [Python | CLI]

But, https://github.com/zestyping/q is a debug tool. I think https://github.com/harelba/q is the right link.

**Comment by alexhallam** [comment]
@chasing-freedom In the spirit of collaboration, if you are interesting in contributing I can leave this open for you. If not then I can fix it at a later date.

**Comment by chasing-freedom** [comment]
> @chasing-freedom In the spirit of collaboration, if you are interesting in contributing I can leave this open for you. If not then I can fix it at a later date.

Thank you for inviting me. I create a pull request. 😁
