### ISSUE TITLE
Right align all numbers by default

### ISSUE THREAD

**Issue by honzajde** [alexhallam/tv#153]
It's a good practice to right-align numbers to the right side. Not sure why this is not case for (positive) integers in `tv`?
Also line numbers that `tv` prints are right aligned....

**Comment by alexhallam** [comment]
I the bottom of the read me I state that my formatting inspiration come from another package I have come to enjoy. I make changes to formatting when my output is not aligned to the 'tibble' package. An example of that may be seen in this issue https://github.com/alexhallam/tv/issues/141

I will see if what you are describing is not aligned to 'tibble' and make changes accordingly.
