### ISSUE TITLE
Tolerate unequal numbers of records per line

### ISSUE THREAD

**Issue by eyalroz** [alexhallam/tv#162]
If I try to view this file:
```
one,two,three
four,five
```
with the latest release, I get:
```
thread 'main' panicked at 'a csv record: Error(UnequalLengths { pos: Some(Position { byte: 14, line: 2, record: 1 }), expected_len: 3, len: 2 })', src/main.rs:388:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
this is too strict. The viewer should accommodate such cases... of course, when this happens, performance will deteriorate, but - that's not a problem (as long as the "happy case" of same-number-of-lines is not affected).

**Comment by alexhallam** [comment]
This violates the csv [rfc4180](https://datatracker.ietf.org/doc/html/rfc4180#page-2) specification, part 4.

> Each line should contain the same
       number of fields throughout the file

**Comment by alexhallam** [comment]
You could fill empty fields with the text `NA` for a solution

**Comment by alexhallam** [comment]
You can also just add a comma

```
one,two,three
four,five,,
```

**Comment by eyalroz** [comment]
@alexhallam : I may not know about the situation until I launch the viewer. I just see a large mess of wrapped text, quotes and commas.

Yes, I realize that the CSV spec requires an equal number of records per line, but - a lot of CSVs don't follow the spec properly. A viewer should handle this situation more gracefully than just rejecting the file outright.

**Comment by alexhallam** [comment]
> I just see a large mess of wrapped text, quotes and commas.

You should see a panic saying where the problem in the csv is. I see in your fist post you showed a Rust panic. This is the expected behavior? From my perspective this seems like the correct thing to do.

What is lacking?

**Comment by eyalroz** [comment]
> You should see a panic saying where the problem in the csv is. I see in your fist post you showed a Rust panic. This is the expected behavior?

No, it is not. That is, yes, I expect to get some message on the standard error stream telling me about the syntax error in the file, but - I expect to the viewer to recover from this error. A reasonable recovery would be rendering the missing fields as empty, and continuing on to the next record; and I expect that to happen as well.

That's what csv-look does, for example:
```
$ csvlook --no-inference /tmp/a.csv 
/usr/lib/python3/dist-packages/agate/table/from_csv.py:74: RuntimeWarning: Error sniffing CSV dialect: Could not determine delimiter
| one  | two  | three |
| ---- | ---- | ----- |
| four | five |       |
|      |      |       |
```

**Comment by alexhallam** [comment]
Thanks for the details a I understand what you are saying and it is a good point. 

At this time my opinion is that this conflates csv *fixing* and *viewing*. I think *fixing* can be a cli on its own.

I have no plans to fix this now.
