### ISSUE TITLE
Fail on windows

### ISSUE THREAD

**Issue by kpym** [alexhallam/tv#169]
I tried tv (version 1.5.2) under windows (GitBash, cmd and Powershell) and it fails on this simple csv: 
```csv
id,first_name,last_name,email
1,Louis,Washington,
2,Sean,Burton,sean@example.com
3,Peter,Smith,peter@example.com
```
with the following output:
```sh
$ tv test1.csv

        tv dim: 3 x 4
        id first_name last_name
129;172email
     1 1 Louis Washington
97;106mNA
     2 2 Sean Burton
222;233msean@example.com
     3 3 Peter Smith
222;233mpeter@example.com
```
![image](https://github.com/alexhallam/tv/assets/3142701/a4136c99-f48e-41cc-a1a0-346b27ade655)
![image](https://github.com/alexhallam/tv/assets/3142701/d02eb8a8-2787-4303-8854-4c3706a20e9f)

**Comment by alexhallam** [comment]
odd. Let me give it a try on my windows.

**Comment by alexhallam** [comment]
Okay, I am running in Powershell using `tidy-viewer-1.5.2-i686-pc-windows-msvc.zip`.

I passed this data

```
id,first_name,last_name,email
1,Louis,Washington,
2,Sean,Burton,sean@example.com
3,Peter,Smith,peter@example.com
```

Here is my output

![image](https://github.com/alexhallam/tv/assets/9298693/d790bd05-48dc-4ae1-8685-9c9196a31a1b)

This is the line I used, ` .\tidy-viewer.exe .\test.csv`

**Comment by alexhallam** [comment]
I would ask you to tell me more about your environment, but I honestly am not sure what to ask. Maybe you can send me anything that could be useful and I can try to get a better picture together.

**Comment by kpym** [comment]
Looks like a terminal problem. 
- In VS Code Terminal : it is ok (but the text is wrapped for bash)
  ![image](https://github.com/alexhallam/tv/assets/3142701/824d5ce7-fffb-437d-abfd-ff4c32d20909)

- In Terminal Windows : it is ok (powershell and cmd)
  ![image](https://github.com/alexhallam/tv/assets/3142701/37f7b720-ae95-4153-848c-94c0f358c232)

- In Powershell Terminal and GitBash Terminal I can't reproduce the previous failure.

You can probably close this issue because it looks like that the problem is probably related to my terminal configuration.
Sorry for that.
