### ISSUE TITLE
The current release tgz will leads to wrong ownership

### ISSUE THREAD

**Issue by xtay573269555** [alexhallam/tv#172]
The current release tgz file ` tidy-viewer-1.5.2.tgz` will leads to wrong ownership(1000:1000) for `/root` after extracting it if you are in `/root` directory.

**Comment by alexhallam** [comment]
Thanks for opening this. 

I will look into how the tarball is created and ensure that it doesn't contain specific metadata about ownership or permissions that could affect the system it's extracted on. 

This might involve changing tarball creation commands or settings to avoid preserving the original file's ownership and permissions.

I think what is going on is that there is a permission related to the staging folder. Maybe if I change the permissions this would fix the issue.

Here is the problem line.

https://github.com/alexhallam/tv/blob/936cf88ca55600df6361a1ca2709bdb51dfc4620/.github/workflows/release.yml#L176

Maybe I should add something like this before running tar.

```bash
chmod -R 755 $staging  # This command recursively sets read, write, and execute permissions
chown -R root:root $staging  # This command recursively changes the owner and group of the staging directory to root.
```

To the best of my knowledge, these commands ensure that the files and directories within staging have a consistent and expected set of permissions and ownership before being archived.
