### ISSUE TITLE
It would help a lot if the tool could handle CSVs that have more columns than column names

### ISSUE THREAD

**Issue by RamRS** [alexhallam/tv#174]
All files exported by R for objects with rownames contain one more column per data row than in the header. It would be great if tv could handle that. If not, I'd need to `awk -F, 'NR==1{print rowname,$0}' file | tv`.

**Comment by alexhallam** [comment]
Thanks @RamRS. Can you give me a reproducible example to work from? I am not tracking.

**Comment by RamRS** [comment]
Sure thing! Here it is: https://gist.github.com/RamRS/1776ae795341270c035aa9c86f102ada

Please let me know if you need more lines.

**Comment by alexhallam** [comment]
Maybe an distinct cli that works like R's `janitor` would be a good option here.

**Comment by RamRS** [comment]
This is definitely closer. If we could add the `x_1` at the beginning and have it customizable, we'd be all set. For example, this is what I do when I'm eyeballing this matrix:

    echo -n "gene," && head xyz.csv | column -ts, | less -S

**Comment by alexhallam** [comment]
Hmm, it is hard to know as a developer if a user wants the first row filled or the last row filled.

I started this project to sort out this specific problem. Please open as many issues as you like on that page. Lay out any example and suggestions from a user experience perspective and I can work it out. 

https://github.com/alexhallam/mop

**Comment by RamRS** [comment]
@alexhallam Alex, thank you for looking into this and having this conversation with me.
