### ISSUE TITLE
Homebrew install

### ISSUE THREAD

**Issue by jimbru** [alexhallam/tv#47]
It would be great to see this installable on Mac via Homebrew!

**Comment by alexhallam** [comment]
I followed this [tutorial](https://federicoterzi.com/blog/how-to-publish-your-rust-project-on-homebrew/). The problem is that I do not have a Mac available. I am looking someone to run the commands below.

```
brew tap alexhallam/tidy-viewer
brew install tidy-viewer
```
@jimbru could you try this out?

**Comment by franciscolourenco** [comment]
Could we add the formula to https://github.com/Homebrew/homebrew-core ?

**Comment by alexhallam** [comment]
Sure, I can work on this.

**Comment by alexhallam** [comment]
> Could we add the formula to https://github.com/Homebrew/homebrew-core ?

Sure I can work on this.

**Comment by alexhallam** [comment]
Contributing to homebrew-core is a little difficult without a Mac to test the Formula on before pushing. I am not sure this is something I can maintain at this time.

**Comment by alexhallam** [comment]
Closed until I get a Mac environment to develop on.

**Comment by MarcAurel** [comment]
https://github.com/Homebrew/homebrew-core/pull/92031

**Comment by MarcAurel** [comment]
@alexhallam there is now [a dedicated formula for tidy-viewer in Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core/blob/master/Formula/tidy-viewer.rb).
No `brew tap` required anymore, a simple `brew install tidy-viewer` should work.

**Comment by alexhallam** [comment]
Thanks a lot @MarcAurel! I will update the install instructions!
