### ISSUE TITLE
Lower required libc6 version if possible

### ISSUE THREAD

**Issue by Mejari** [alexhallam/tv#52]
Using Ubuntu 16.04 LTS, the version of libc6 installed is 2.23-0ubuntu11.3. Attempting to install tidy-viewer via dpkg gives the following error:

    dpkg: dependency problems prevent configuration of tidy-viewer:
     tidy-viewer depends on libc6 (>= 2.31); however:
      Version of libc6:amd64 on system is 2.23-0ubuntu11.3.

If nothing between versions 2.23 and 2.31 is needed it would be nice to lower the required version to increase the number of systems tidy-viewer can be installed on.

**Comment by alexhallam** [comment]
Thanks for opening this. I want this package to be more accessible. I need to see what is requiring this libc version

**Comment by iamjameswalters** [comment]
@alexhallam might still be looking into the libc version, but at least in the meantime @Mejari, `tidy-viewer` is now available as a snap, which should install fine on your 16.04 system. You can install it with `snap install tidy-viewer --edge`.

**Comment by Mejari** [comment]
Unfortunately for me I'm using Ubuntu via the Windows subsystem, which has snap disabled. But I'm sure having it available through there will be very useful in general.

**Comment by alexhallam** [comment]
I would like to make sure this can work for you @Mejari . With some help from the good volunteers on the Rust Discord channel took a look at the `tree` today with `cargo tree`

```sh
tidy-viewer v0.0.19 (/home/user/code/rs/tv)
├── console v0.14.1
│   ├── lazy_static v1.4.0
│   ├── libc v0.2.94
│   ├── regex v1.4.6
│   │   ├── aho-corasick v0.7.15
│   │   │   └── memchr v2.3.4
│   │   ├── memchr v2.3.4
│   │   └── regex-syntax v0.6.23
│   ├── terminal_size v0.1.16
│   │   └── libc v0.2.94
│   └── unicode-width v0.1.8
├── crossterm v0.20.0
│   ├── bitflags v1.2.1
│   ├── libc v0.2.94
│   ├── mio v0.7.13
│   │   ├── libc v0.2.94
│   │   └── log v0.4.14
│   │       └── cfg-if v1.0.0
│   ├── parking_lot v0.11.1
│   │   ├── instant v0.1.10
│   │   │   └── cfg-if v1.0.0
│   │   ├── lock_api v0.4.4
│   │   │   └── scopeguard v1.1.0
│   │   └── parking_lot_core v0.8.3
│   │       ├── cfg-if v1.0.0
│   │       ├── instant v0.1.10 (*)
│   │       ├── libc v0.2.94
│   │       └── smallvec v1.6.1
│   ├── signal-hook v0.3.9
│   │   ├── libc v0.2.94
│   │   └── signal-hook-registry v1.4.0
│   │       └── libc v0.2.94
│   └── signal-hook-mio v0.2.1
│       ├── libc v0.2.94
│       ├── mio v0.7.13 (*)
│       └── signal-hook v0.3.9 (*)
├── regex v1.4.6 (*)
├── structopt v0.3.21
│   ├── clap v2.33.3
│   │   ├── ansi_term v0.11.0
│   │   ├── atty v0.2.14
│   │   │   └── libc v0.2.94

```

I may be able to grab lower visions of some of these libraries. The requirement for libc 0.2.94 froms from three libraries `console`, `crossterm`,`structopt`.

### console
I am pretty sure this is old code and needs to be removed. I was using this before I started using crossterm.

### crossterm
I use this to get terminal dimensions across platforms. I could not remove it, but I could try using some older versions. 

### structopt
This is the core of the cli options/flags. I could not remove it, but I could try using some older versions.

**Comment by alexhallam** [comment]
Alternatively can you install the windows binary?

**Comment by alexhallam** [comment]
On linux do

```sh
wget https://github.com/alexhallam/tv/releases/download/0.0.20/tidy-viewer--x86_64-unknown-linux-musl.tar.gz
tar -xvzf tidy-viewer--x86_64-unknown-linux-musl.tar.gz
cd tidy-viewer--x86_64-unknown-linux-musl
```

at this point you should see `tidy-viewer`. Let me know if you still have issues.
