### ISSUE TITLE
Publish as a Snap

### ISSUE THREAD

**Issue by iamjameswalters** [alexhallam/tv#57]
Hi there! Saw this tool on Show HN, and thought it was worth snapping. I've opened #56 with a working `snapcraft.yaml`.

Would the upstream project be interested in putting this utility on the [Snap Store](http://snapcraft.io)? If not, I would be interested in doing so myself.

**Comment by alexhallam** [comment]
Of course! Thanks for volunteering!

**Comment by alexhallam** [comment]
[![Get it from the Snap Store](https://snapcraft.io/static/images/badges/en/snap-store-black.svg)](https://snapcraft.io/tidy-viewer)

**Comment by alexhallam** [comment]
It looks like version 0.0.11 is being pulled. I need to look into why it is not pulling 0.0.13.

**Comment by iamjameswalters** [comment]
I think it's building the latest version, but perhaps the tag's out of date?

On an up-to-date `main`, `git describe --tags --abbrev=0` (where `snapcraft.yaml` is pulling its version string) outputs `0.0.0.11-alpha`.

**Comment by alexhallam** [comment]
I am going to leave this issue open as a reminder to check on the releases. I think they all need to be bumped.

**Comment by iamjameswalters** [comment]
Gotcha.

Also, now that you've got it on the store, you'll find documentation for [automatically building off Github here](https://snapcraft.io/docs/build-from-github). Just add an `architectures` key to `snapcraft.yaml` so Launchpad knows what to build for, and point it at your repo. Should be cake from that point on!

**Comment by alexhallam** [comment]
I appreciate the help.

**Comment by iamjameswalters** [comment]
No problem, thanks for letting me contribute! Feel free to tag me if there's anything else I can help you with re: the snap.

**Comment by alexhallam** [comment]
Closed with #61
