### ISSUE TITLE
[Looking for MacOS User Input] - Check background values on NAs

### ISSUE THREAD

**Issue by alexhallam** [alexhallam/tv#68]
Just pulled `tv` on MacOS and saw that the NA values, which should only be colored, seem to have a background effect. I am not sure if this is an issue with the default terminal, the light theme, or `tv`. 

I just want to open this issue to verify that `tv` is not doing any additional background effects for NAs.

I would love feedback from Mac Users who may use different terminal emulators or different themes. I am using the default terminal app.

To reproduce do the following:

```sh
# Download and untar (tar -xvzf) the apple-darwin release.
curl https://raw.githubusercontent.com/alexhallam/tv/main/data/a.csv -o a.csv
cat a.csv | ./tidy-viewer
```

<img width="379" alt="Screen Shot 2021-09-30 at 7 28 06 AM" src="https://user-images.githubusercontent.com/9298693/135447077-e22c7fe6-826b-44ea-af1e-7a261d3e3587.png">

**Comment by alexhallam** [comment]
No input from users. Assume no interest.

**Comment by jakemcannon** [comment]
Default terminal:
<img width="431" alt="Screen Shot 2021-11-24 at 11 17 48 AM" src="https://user-images.githubusercontent.com/24326978/143275595-f271c9aa-e8ca-47a7-89e7-9bcf9ebc8ba6.png">

iTerm2:
<img width="375" alt="Screen Shot 2021-11-24 at 11 18 19 AM" src="https://user-images.githubusercontent.com/24326978/143275898-b0f06583-8076-4dff-895c-8f8c7dc07740.png">

**Comment by alexhallam** [comment]
Thanks @jakemcannon. It looks like iTerm2 is recommended over the default terminal. Thanks for showing some results!
