### ISSUE TITLE
Implement sigfig option

### ISSUE THREAD

**Issue by alexhallam** [alexhallam/tv#72]
Currently sigfigs are set to 3. The user should be able to specify this.

**Comment by alexhallam** [comment]
I am going to claim this one.

**Comment by rlewicki** [comment]
Hey @alexhallam, I started looking into this issue but I noticed that it works slightly different than I would have expected. My thought was that `sigfig` property defines number of decimal numbers to display. So. for example, number `123.1234` with `sigfig=2` would end up with result `123.12`. However it seems it's currently taking into account both `lhs` and `rhs` and  the output is very hard to understand.

Here is  the example input I used:
```
numbers
123
123.456
123.4
12.345
1.2345
1234.56
0.12345
0.0123
```

Here is tv's output with `sigfig=3` (default):
```
      tv dim: 8 x 1
      numbers
1      123
2      123.
3      123.
4       12.3
5        1.23
6     1234.
7        0.123
8        0.0123
```

Here is tv's output with `sigfig=1`:
```
      tv dim: 8 x 1
      numbers
1      123
2      123.
3      123.
4       12.
5        1.
6     1234.
7        0.1
8        0.01
```

What do you think is happening here?

**Comment by rlewicki** [comment]
Ah, I wasn't aware that it work this way! In that case here are examples with negative numbers as well.

1. `sigfig=1`
```
      tv dim: 8 x 2
      numbers neg_numbers
1      123     -123
2      123.    -123.
3      123.    -123.
4       12.     -12.
5        1.      -1.
6     1234.   -1234.
7        0.1     -0.1
8        0.01    -0.01
```
2. `sigfig=3` (default)
```
      tv dim: 8 x 2
      numbers   neg_numbers
1      123       -123
2      123.      -123.
3      123.      -123.
4       12.3      -12.3
5        1.23      -1.23
6     1234.     -1234.
7        0.123     -0.123
8        0.0123    -0.0123
```
3. `sigfig=5`
```
      tv dim: 8 x 2
      numbers    neg_numbers
1      123        -123
2      123.45     -123.4
3      123.4      -123.4
4       12.345     -12.34
5        1.2345     -1.2345
6     1234.5     -1234.
7        0.12345    -0.12345
8        0.0123     -0.0123
```

If this is alright I'll put up a review with my changes.

**Comment by rlewicki** [comment]
I’m short on time in upcoming days, I’ll continue working on this next week. I’ll keep you updated how this is going :)

21 Oct 2021, 13:31 by ***@***.***:
