### ISSUE TITLE
atty?

### ISSUE THREAD

**Issue by alexhallam** [alexhallam/tv#73]
Use the `atty` create to know if stdout is being pipes to `tty` make conditions to error gracefully.

**Comment by rlewicki** [comment]
Thanks for explaining this. I'll have a look into it.

**Comment by alexhallam** [comment]
This is great.!

So I can replicate everything except for the last example `less test.csv | tv` gives a properly formatted table. We can look into why that is later. 

I think the solution is to uncolor all of the values if `i'm not a tty` is true. It will just require some repetitive code blocks. For every block of code that adds color there will have to be an complimentary, uncolored option.

**Comment by rlewicki** [comment]
Awesome, I'll prepare a PR for that then!

**Comment by alexhallam** [comment]
Closed with #95
